#include "dbus/SAPMPris.h"
#include <QDebug>
#include <QtDBus/qdbusconnection.h>
#include <qdbusextratypes.h>
#include <qdbusmessage.h>
#include <qtmetamacros.h>

// MPRIS adaptator generated by Qt.
#include "dbus/mprisRoot.h"
#include "dbus/mprisPlayer.h"

const char* SAPMPris::_serviceName = "org.mpris.MediaPlayer2.simpleaudioplayer";
const char* SAPMPris::_mprisObjectPath = "/org/mpris/MediaPlayer2";
const char* SAPMPris::_freeDesktopPath = "org.freedesktop.DBus.Properties";
const char* SAPMPris::_propertyChangedStr = "PropertiesChanged";
const char* SAPMPris::_mprisPlayerEntity = "org.mpris.MediaPlayer2.Player";

SAPMPris::SAPMPris(QObject* parent) :
    QObject(parent),
    m_canPause(false),
    m_canPlay(false),
    m_canNext(false),
    m_canPrevious(false),
    m_canControl(false)
{
    // Instanciate the adaptator.
    new MPrisRoot(this);
    new MPrisPlayer(this);

    QDBusConnection::sessionBus().registerService(_serviceName);
    QDBusConnection::sessionBus().registerObject(
        _mprisObjectPath, 
        this);
}

SAPMPris::~SAPMPris()
{}

/*
Root MRPIS
*/
void SAPMPris::Raise()
{
    // Tell the application to raise and focus the window.
    emit raise();
}

void SAPMPris::Quit()
{}

bool SAPMPris::canQuit() const
{
    return false;
}

bool SAPMPris::canRaise() const
{
    return true;
}

bool SAPMPris::hasTrackList() const
{
    return false;
}

QString SAPMPris::identity() const
{
    return "simple-audio-player";
}

QStringList SAPMPris::supportedUriSchemes() const
{
    return QStringList();
}

QStringList SAPMPris::supportedMimeTypes() const
{
    return {};
}

/*
Player MPRIS
*/
void SAPMPris::Next()
{
    emit next(); // Notify the application to go to the next track.
}

void SAPMPris::Previous()
{
    emit previous(); // Notify the application to restart or go to the previous track.
}

void SAPMPris::Pause()
{
    emit playPause();
}

void SAPMPris::PlayPause()
{
    emit playPause();
}

void SAPMPris::Stop()
{}

void SAPMPris::Play()
{
    emit playPause();
}

void SAPMPris::Seek(long long offset)
{}

void SAPMPris::SetPosition(const QDBusObjectPath &id, long long position)
{}

void SAPMPris::OpenUri(const QString& uri)
{}

QString SAPMPris::playbackStatus() const
{
    return m_playbackStatus;
}

void SAPMPris::setPlaybackStatus(PlaybackStatus status)
{
    // Updating the playback status.
    m_playbackStatus = playbackStatusEnumToString(status);

    // Notify MPRIS of the change.
    notify(NotifyType::PLAYBACK_STATUS);

    // Change CanPlay, CanPause, CanNext, CanPrevious and CanControl base and playing status
    if (status == PlaybackStatus::PLAYING)
    {
        m_canControl = true;
        m_canPlay = true;
        m_canPause = true;
        m_canPrevious = true;
    }
    else
    {
        m_canControl = false;
        m_canPause = false;
        m_canPlay = false;
        m_canPrevious = false;
        m_canNext = false;
    }

    // Notify mpris of the change.
    if (status != PlaybackStatus::PAUSED)
    {
        notify(NotifyType::CAN_CONTROL);
        notify(NotifyType::CAN_PLAY);
        notify(NotifyType::CAN_PAUSE);
        notify(NotifyType::CAN_PREVIOUS);
    }
    if (status == PlaybackStatus::STOPPED)
    {
        notify(NotifyType::CAN_NEXT);
    }
}

double SAPMPris::rate() const
{
    return 1.0;
}

void SAPMPris::setRate(double rate)
{}

QVariantMap SAPMPris::metadata() const
{
    return m_metadata;
}

void SAPMPris::setMetadata(const MetaData& data)
{
    m_metadata = data.toVariantMap();

    // Notify MPRIS of the change.
    notify(NotifyType::METADATA);
}

double SAPMPris::volume() const
{
    return 1.0;
}

void SAPMPris::setVolume(double volume)
{}

long long SAPMPris::position() const
{
    return m_position;
}

void SAPMPris::setPosition(long long position)
{
    m_position = position * 1000; // Convert millisecond value to microsecond.
}

double SAPMPris::minimumRate() const
{
    return 1.0;
}

double SAPMPris::maximumRate() const
{
    return 1.0;
}

bool SAPMPris::canNext() const
{
    return m_canNext;
}

void SAPMPris::setCanNext(bool value)
{
    m_canNext = value;
    notify(NotifyType::CAN_NEXT);
}

bool SAPMPris::canPrevious() const
{
    return m_canPrevious;
}

bool SAPMPris::canPlay() const
{
    return m_canPlay;
}

bool SAPMPris::canPause() const
{
    return m_canPause;
}

bool SAPMPris::canSeek() const
{
    return false;
}

bool SAPMPris::canControl() const
{
    return m_canControl;
}

/*
Helper methods
*/
QString SAPMPris::playbackStatusEnumToString(PlaybackStatus status)
{
    // Converting the enum class PlaybackStatus to string for dbus.
    if (status == PlaybackStatus::PLAYING)
        return "Playing";
    else if (status == PlaybackStatus::PAUSED)
        return "Paused";
    else
        return "Stopped";
}

QVariantMap SAPMPris::MetaData::toVariantMap() const
{
    // Convert MetaData to valid dbus values.
    QVariantMap map;
    map["mpris:trackid"] = QDBusObjectPath(QString("/simpleaudioplayer/%1").arg(trackID));
    map["xesam:title"] = title;
    map["xesam:album"] = album;

    // Track Artists
    QStringList listArtists;
    listArtists.append(artists);
    map["xesam:artist"] = listArtists;
    return map;
}

QString SAPMPris::notifyTypeToString(NotifyType type)
{
    // Converting the NotifyType to a string value for MPRIS.
    if (type == NotifyType::PLAYBACK_STATUS)
    {
        return "PlaybackStatus";
    }
    else if (type == NotifyType::METADATA)
    {
        return "Metadata";
    }
    else if (type == NotifyType::CAN_CONTROL)
    {
        return "CanControl";
    }
    else if (type == NotifyType::CAN_PLAY)
    {
        return "CanPlay";
    }
    else if (type == NotifyType::CAN_PAUSE)
    {
        return "CanPause";
    }
    else if (type == NotifyType::CAN_PREVIOUS)
    {
        return "CanGoPrevious";
    }
    else if (type == NotifyType::CAN_NEXT)
    {
        return "CanGoNext";
    }
    else 
    {
        return "";
    }
}

QVariant SAPMPris::getNotifyValue(NotifyType type)
{
    if (type == NotifyType::PLAYBACK_STATUS)
    {
        return m_playbackStatus;
    }
    else if (type == NotifyType::METADATA)
    {
        return m_metadata;
    }
    else if (type == NotifyType::CAN_CONTROL)
    {
        return m_canControl;
    }
    else if (type == NotifyType::CAN_PLAY)
    {
        return m_canPlay;
    }
    else if (type == NotifyType::CAN_PAUSE)
    {
        return m_canPause;
    }
    else if (type == NotifyType::CAN_PREVIOUS)
    {
        return m_canPrevious;
    }
    else if (type == NotifyType::CAN_NEXT)
    {
        return m_canNext;
    }
    else 
    {
        return QVariant();
    }
}

void SAPMPris::notify(NotifyType type, const QVariant& value)
{
    // Checking if the notify type is valid.
    if (type != NotifyType::UNKNOWN && value.isValid())
    {
        QString propertyName = notifyTypeToString(type);

        // Creating a DBus signal.
        QDBusMessage signal = QDBusMessage::createSignal(
            _mprisObjectPath, _freeDesktopPath, _propertyChangedStr);
        
        // Storing the property name and the new value into a variant map.
        QVariantMap map;
        map[propertyName] = value;

        // Creating the message args with the MPRIS entity (player), the property change and an empty string list.
        QVariantList args;
        args.append(_mprisPlayerEntity);
        args.append(map);
        args.append(QStringList());

        // Set the args into the signal.
        signal.setArguments(args);

        // Send the signal.
        QDBusConnection::sessionBus().send(signal);
    }
}

void SAPMPris::notify(NotifyType type)
{
    /*
    Getting the value based on the notify type 
    and send it to the other notify method.
    */
    const QVariant value = getNotifyValue(type);
    notify(type, value);
}
